// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYanRSEDJulfHI8JxwllztuMbszJD6zq0',
    appId: '1:586166112416:web:9827e030a30fb5730079c5',
    messagingSenderId: '586166112416',
    projectId: 'animalrescue-3cff4',
    authDomain: 'animalrescue-3cff4.firebaseapp.com',
    storageBucket: 'animalrescue-3cff4.firebasestorage.app',
    measurementId: 'G-B12X7XFXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJvLj2N7eG6CTYqGaEsZnYk19qvF3Bak',
    appId: '1:586166112416:android:ce25f0f4c1fd89a10079c5',
    messagingSenderId: '586166112416',
    projectId: 'animalrescue-3cff4',
    storageBucket: 'animalrescue-3cff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXbglTGeJKr2FTHDiwWrOqM-BV6rj7Jw',
    appId: '1:586166112416:ios:9182a0708df570a10079c5',
    messagingSenderId: '586166112416',
    projectId: 'animalrescue-3cff4',
    storageBucket: 'animalrescue-3cff4.firebasestorage.app',
    androidClientId: '586166112416-19eqqlfbapg91c2v3hvd4hd978jlkffu.apps.googleusercontent.com',
    iosClientId: '586166112416-qch7mn5a9mbrcobarcm1vtlf7sahd6oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalrescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQXbglTGeJKr2FTHDiwWrOqM-BV6rj7Jw',
    appId: '1:586166112416:ios:9182a0708df570a10079c5',
    messagingSenderId: '586166112416',
    projectId: 'animalrescue-3cff4',
    storageBucket: 'animalrescue-3cff4.firebasestorage.app',
    androidClientId: '586166112416-19eqqlfbapg91c2v3hvd4hd978jlkffu.apps.googleusercontent.com',
    iosClientId: '586166112416-qch7mn5a9mbrcobarcm1vtlf7sahd6oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalrescue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYanRSEDJulfHI8JxwllztuMbszJD6zq0',
    appId: '1:586166112416:web:e51c0a95c769c9560079c5',
    messagingSenderId: '586166112416',
    projectId: 'animalrescue-3cff4',
    authDomain: 'animalrescue-3cff4.firebaseapp.com',
    storageBucket: 'animalrescue-3cff4.firebasestorage.app',
    measurementId: 'G-TXK8ZYZ5W7',
  );
}
